DROP DATABASE IF EXISTS patholog;
CREATE DATABASE patholog;

use patholog;

DROP TABLE IF EXISTS users; /*CREATE OR REPLACE TABLE*/
DROP TABLE IF EXISTS patients;

CREATE TABLE users(
 id int AUTO_INCREMENT,
 fullName VARCHAR(255) NOT NULL UNIQUE,
 pass VARCHAR(255) NOT NULL,
 phone VARCHAR(10) NOT NULL UNIQUE,
 email VARCHAR(255) NOT NULL UNIQUE,
 rank VARCHAR(255) NOT NULL,
 login VARCHAR(255) NOT NULL UNIQUE,
 PRIMARY KEY(id)
);


