DROP DATABASE IF EXISTS EbayDB;
CREATE DATABASE EbayDB;

use EbayDB;

DROP TABLE IF EXISTS users; /*CREATE OR REPLACE TABLE*/
DROP TABLE IF EXISTS products;

CREATE TABLE users(
 id int AUTO_INCREMENT,
 fullname VARCHAR(255) NOT NULL,
 pass VARCHAR(255),
 phone VARCHAR(10) UNIQUE,
 email VARCHAR(255) NOT NULL UNIQUE,
 PRIMARY KEY(id)
);

CREATE TABLE products(
 id int AUTO_INCREMENT,
 title VARCHAR(255) NOT NULL,
 description VARCHAR(255),
 price int,
 user_id int NOT NULL,
 PRIMARY KEY(id),
 FOREIGN KEY(user_id) REFERENCES users(id)
);
